version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #     # - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017/payload
  #     - PORT=3000
  #     - PAYLOAD_SECRET=TESTING

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    restart: always

volumes:
  data:
  # node_modules:
