[package]
name = "serde-jsonformat-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = ["derive"] }
serde = "1.0.145"
serde_json = "1.0.85"
serde_yaml = "0.9.13"
