version: '3.8'

services:
  spark:
    image: bitnami/spark
    ports:
      - 4040:4040
      - 8080:8080
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark
    ports:
      - 8081:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
