version: '3.8'

services:
  # nginx:
  #   image: nginx
  #   logging:
  #     driver: loki
  #     options: 
  #       loki-url: http://loki:3100/loki/api/v1/push
  #   ports: 
  #     - 8080:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/index.html:/var/www/html/index.html
  #   depends_on: 
  #     - loki

  # loki:
  #   image: grafana/loki
  #   ports:
  #     - 3100:3100
  #   command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
