version: '3'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: aaa
      SECRET: bbb 
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: d1r3ctu5
      DB_CLIENT: sqlite3
      DB_FILENAME: data.db
      WEBSOCKETS_ENABLED: true
