import MiniSearch from 'minisearch'
import { MouseEventHandler, useRef, useState } from 'react'
import { useMiniSearch } from 'react-minisearch'

// These sentences are generated by chatgpt
const documents = [
  {
    id: 1,
    name: '東京',
    description: '東京（とうきょう）は、日本の首都であり、最も人口の多い都市です。東京は多彩な文化、歴史的な名所、現代的な建築物、美食、エンターテインメントが共存する都市で、世界的に有名です。',
    country: '日本',
  },
  {
    id: 2,
    name: 'ニューヨーク',
    description: 'ニューヨーク（New York）は、アメリカ合衆国の東部に位置し、国内最大の都市であり、国際的な金融センターとしても知られています。ニューヨークは高層ビル、ブロードウェイ、セントラルパークなど多くのアイコニックな観光スポットがあります。',
    country: 'アメリカ',
  },
  {
    id: 3,
    name: 'ロンドン',
    description: 'ロンドン（London）は、イギリスの首都であり、多くの歴史的な名所、美術館、シアター、ショッピングエリアがあります。ロンドンは多様な文化と国際的な多元性が共存する都市です。',
    country: 'イギリス',
  },
  {
    id: 4,
    name: 'パリ',
    description: 'パリ（Paris）は、フランスの首都であり、エッフェル塔、ルーブル美術館、シャンゼリゼ通りなど、美しい観光スポットで知られています。パリはファッション、美食、芸術の中心として世界的に評価されています。',
    country: 'フランス',
  },
];

export const Search = () => {
  const { search, searchResults } = useMiniSearch(documents, {
    fields: ['name', 'description'],
    storeFields: ['name'],
    searchOptions: {
      // boost: { description: 2 },
      // fuzzy: 0.2
    }
  })

  const keyword = useRef<HTMLInputElement>(null)

  const handleSearch: MouseEventHandler<HTMLButtonElement> = (e) => {
    e.preventDefault()
    const searchText = keyword.current?.value ?? 'hey'
    search(searchText)
  }
  console.log(searchResults)

  return (
    <>
      <input type='text' ref={keyword} />
      <button onClick={handleSearch}>search</button>
    </>
  )
}
