[package]
name = "aero-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
axum = { version = "0.6.18", features = ["multipart"] }
couch_rs = "0.9.2"
dirs = "5.0.1"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
tower = "0.4.13"
wasmtime = "8.0.1"
