[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "waveslib"
description = "test"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
wasm-bindgen = "0.2.84"