name = "flywaywind-api"
compatibility_date = "2023-01-01" # cloudformationのversion的な。

# 内部的にはKVっぽい。Cloudflare Pages が推奨されている
# [site]
# bucket = "./assets"

kv_namespaces = [
  { binding = "MY_KV", id = "a2d5f9a828b343599241535be00963df" }
]

[[rules]]
type = "CompiledWasm"
globs = ["./src/main.wasm"]


[[rules]]
type = "ESModule"
globs = ["./src/wasm_exec.js"]
