[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "fncore"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwith_formatter = { git = "https://github.com/enuesaa/jsonwith", version = "0.1.0" }
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.84"
